// ASX Index Data — S&P/ASX March 2026 Rebalance
// Effective 23 March 2026 | Source: S&P Dow Jones Indices
// Auto-generated — do not edit manually

const ASX_DATA = {
  "360": { ticker:"360", company:"Life360", sector:"Information Technology", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "4DX": { ticker:"4DX", company:"4DMedical", sector:"Health Care", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "A2M": { ticker:"A2M", company:"The a2 Milk Company", sector:"Consumer Staples", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ABB": { ticker:"ABB", company:"Aussie Broadband", sector:"Communication Services", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ABY": { ticker:"ABY", company:"Adore Beauty Group", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AEF": { ticker:"AEF", company:"Australian Ethical Investment", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AFI": { ticker:"AFI", company:"Australian Foundation Investment", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "AGL": { ticker:"AGL", company:"AGL Energy", sector:"Utilities", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AIA": { ticker:"AIA", company:"Auckland International Airport", sector:"Industrials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "AIZ": { ticker:"AIZ", company:"Air New Zealand", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ALD": { ticker:"ALD", company:"Ampol", sector:"Energy", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ALL": { ticker:"ALL", company:"Aristocrat Leisure", sector:"Consumer Discretionary", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "ALQ": { ticker:"ALQ", company:"ALS Limited", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ALX": { ticker:"ALX", company:"Atlas Arteria", sector:"Industrials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AMC": { ticker:"AMC", company:"Amcor", sector:"Materials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AMP": { ticker:"AMP", company:"AMP Limited", sector:"Financials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ANN": { ticker:"ANN", company:"Ansell", sector:"Health Care", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "ANZ": { ticker:"ANZ", company:"ANZ Group Holdings", sector:"Financials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "APA": { ticker:"APA", company:"APA Group", sector:"Utilities", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "APE": { ticker:"APE", company:"Eagers Automotive", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "APM": { ticker:"APM", company:"APM Human Services", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AQZ": { ticker:"AQZ", company:"Alliance Aviation Services", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ARA": { ticker:"ARA", company:"Arafura Rare Earths", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "ARB": { ticker:"ARB", company:"ARB Corporation", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ARF": { ticker:"ARF", company:"Arena REIT", sector:"Real Estate", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ARG": { ticker:"ARG", company:"Argo Investments", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "ASB": { ticker:"ASB", company:"Austal", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ASX": { ticker:"ASX", company:"ASX Limited", sector:"Financials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AUB": { ticker:"AUB", company:"AUB Group", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AUI": { ticker:"AUI", company:"Australian United Investment", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AX1": { ticker:"AX1", company:"Accent Group", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "AZJ": { ticker:"AZJ", company:"Aurizon Holdings", sector:"Industrials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "BAP": { ticker:"BAP", company:"Bapcor", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BEN": { ticker:"BEN", company:"Bendigo and Adelaide Bank", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BGA": { ticker:"BGA", company:"Bega Cheese", sector:"Consumer Staples", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "BHP": { ticker:"BHP", company:"BHP Group", sector:"Materials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BKI": { ticker:"BKI", company:"BKI Investment Company", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "BKL": { ticker:"BKL", company:"Blackmores", sector:"Consumer Staples", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "BKW": { ticker:"BKW", company:"Brickworks", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "BLD": { ticker:"BLD", company:"Boral", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "BOQ": { ticker:"BOQ", company:"Bank of Queensland", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BPT": { ticker:"BPT", company:"Beach Energy", sector:"Energy", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BRG": { ticker:"BRG", company:"Breville Group", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BSL": { ticker:"BSL", company:"BlueScope Steel", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BWP": { ticker:"BWP", company:"BWP Trust", sector:"Real Estate", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "BXB": { ticker:"BXB", company:"Brambles", sector:"Industrials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CAR": { ticker:"CAR", company:"CAR Group", sector:"Communication Services", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CAT": { ticker:"CAT", company:"Catapult Group International", sector:"Information Technology", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CBA": { ticker:"CBA", company:"Commonwealth Bank of Australia", sector:"Financials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "CDA": { ticker:"CDA", company:"Codan", sector:"Information Technology", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CEN": { ticker:"CEN", company:"Contact Energy", sector:"Utilities", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CGC": { ticker:"CGC", company:"Costa Group Holdings", sector:"Consumer Staples", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CGF": { ticker:"CGF", company:"Challenger", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "CHC": { ticker:"CHC", company:"Charter Hall Group", sector:"Real Estate", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CHN": { ticker:"CHN", company:"Chalice Mining", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CIA": { ticker:"CIA", company:"Champion Iron", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CIP": { ticker:"CIP", company:"Centuria Industrial REIT", sector:"Real Estate", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CKF": { ticker:"CKF", company:"Collins Foods", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CLW": { ticker:"CLW", company:"Charter Hall Long Wale REIT", sector:"Real Estate", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CMM": { ticker:"CMM", company:"Capricorn Metals", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CMW": { ticker:"CMW", company:"Cromwell Property Group", sector:"Real Estate", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CNI": { ticker:"CNI", company:"Centuria Capital Group", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CNU": { ticker:"CNU", company:"Chorus", sector:"Communication Services", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "COH": { ticker:"COH", company:"Cochlear", sector:"Health Care", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "COL": { ticker:"COL", company:"Coles Group", sector:"Consumer Staples", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "CPU": { ticker:"CPU", company:"Computershare", sector:"Industrials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CQE": { ticker:"CQE", company:"Charter Hall Social Infrastructure REIT", sector:"Real Estate", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CQR": { ticker:"CQR", company:"Charter Hall Retail REIT", sector:"Real Estate", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "CRN": { ticker:"CRN", company:"Coronado Global Resources", sector:"Energy", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CSL": { ticker:"CSL", company:"CSL Limited", sector:"Health Care", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "CSR": { ticker:"CSR", company:"CSR Limited", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CTD": { ticker:"CTD", company:"Corporate Travel Management", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CUV": { ticker:"CUV", company:"Clinuvel Pharmaceuticals", sector:"Health Care", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "CWY": { ticker:"CWY", company:"Cleanaway Waste Management", sector:"Industrials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "DBI": { ticker:"DBI", company:"Dalrymple Bay Infrastructure", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DDR": { ticker:"DDR", company:"Dicker Data", sector:"Information Technology", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DEG": { ticker:"DEG", company:"De Grey Mining", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DGL": { ticker:"DGL", company:"DGL Group", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DGT": { ticker:"DGT", company:"DigiCo Infrastructure REIT", sector:"Real Estate", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DHG": { ticker:"DHG", company:"Domain Holdings Australia", sector:"Communication Services", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "DMP": { ticker:"DMP", company:"Domino's Pizza Enterprises", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "DPM": { ticker:"DPM", company:"DPM Metals", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "DRR": { ticker:"DRR", company:"Deterra Royalties", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DTL": { ticker:"DTL", company:"Data#3", sector:"Information Technology", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DUI": { ticker:"DUI", company:"Diversified United Investment", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "DXS": { ticker:"DXS", company:"Dexus", sector:"Real Estate", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "EBO": { ticker:"EBO", company:"EBOS Group", sector:"Health Care", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "EDV": { ticker:"EDV", company:"Endeavour Group", sector:"Consumer Staples", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ELD": { ticker:"ELD", company:"Elders", sector:"Consumer Staples", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ELV": { ticker:"ELV", company:"Elevra Lithium", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "EQT": { ticker:"EQT", company:"EQT Holdings", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "EVN": { ticker:"EVN", company:"Evolution Mining", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "EVT": { ticker:"EVT", company:"EVT Limited", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "FBU": { ticker:"FBU", company:"Fletcher Building", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "FLT": { ticker:"FLT", company:"Flight Centre Travel Group", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "FMG": { ticker:"FMG", company:"Fortescue Limited", sector:"Materials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "FPH": { ticker:"FPH", company:"Fisher & Paykel Healthcare", sector:"Health Care", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GDG": { ticker:"GDG", company:"Generation Development Group", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "GEM": { ticker:"GEM", company:"G8 Education", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GLF": { ticker:"GLF", company:"GemLife Communities Group", sector:"Real Estate", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "GMA": { ticker:"GMA", company:"Genworth Mortgage Insurance", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GMG": { ticker:"GMG", company:"Goodman Group", sector:"Real Estate", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "GNC": { ticker:"GNC", company:"GrainCorp", sector:"Consumer Staples", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GNE": { ticker:"GNE", company:"Genesis Energy", sector:"Utilities", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GOR": { ticker:"GOR", company:"Gold Road Resources", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GOZ": { ticker:"GOZ", company:"Growthpoint Properties", sector:"Real Estate", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GPT": { ticker:"GPT", company:"GPT Group", sector:"Real Estate", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GQG": { ticker:"GQG", company:"GQG Partners", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "GRL": { ticker:"GRL", company:"Greatland Resources", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:true },
  "GTK": { ticker:"GTK", company:"Gentrack Group", sector:"Information Technology", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GUD": { ticker:"GUD", company:"G.U.D. Holdings", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "GWA": { ticker:"GWA", company:"GWA Group", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "HGH": { ticker:"HGH", company:"Heartland Group Holdings", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "HLS": { ticker:"HLS", company:"Healius", sector:"Health Care", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "HM1": { ticker:"HM1", company:"Hearts and Minds Investments", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "HMC": { ticker:"HMC", company:"Home Consortium", sector:"Real Estate", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "HSN": { ticker:"HSN", company:"Hansen Technologies", sector:"Information Technology", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "HUB": { ticker:"HUB", company:"HUB24", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "HVN": { ticker:"HVN", company:"Harvey Norman Holdings", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "IAG": { ticker:"IAG", company:"Insurance Australia Group", sector:"Financials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "IDX": { ticker:"IDX", company:"Integral Diagnostics", sector:"Health Care", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "IEL": { ticker:"IEL", company:"IDP Education", sector:"Consumer Discretionary", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "IFL": { ticker:"IFL", company:"Insignia Financial", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "IGO": { ticker:"IGO", company:"IGO Limited", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "ILU": { ticker:"ILU", company:"Iluka Resources", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "INA": { ticker:"INA", company:"Ingenia Communities Group", sector:"Real Estate", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ING": { ticker:"ING", company:"Inghams Group", sector:"Consumer Staples", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "INR": { ticker:"INR", company:"ioneer", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "IPH": { ticker:"IPH", company:"IPH Limited", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "IPL": { ticker:"IPL", company:"Incitec Pivot", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "IRE": { ticker:"IRE", company:"IRESS", sector:"Information Technology", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "JBH": { ticker:"JBH", company:"JB Hi-Fi", sector:"Consumer Discretionary", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "JHX": { ticker:"JHX", company:"James Hardie Industries", sector:"Materials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "KGN": { ticker:"KGN", company:"Kogan.com", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "KPG": { ticker:"KPG", company:"Kelly Partners Group", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "LFG": { ticker:"LFG", company:"Liberty Financial Group", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "LFS": { ticker:"LFS", company:"Latitude Group Holdings", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "LGI": { ticker:"LGI", company:"LGI Limited", sector:"Utilities", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "LIC": { ticker:"LIC", company:"Lifestyle Communities", sector:"Real Estate", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "LNW": { ticker:"LNW", company:"Light & Wonder", sector:"Consumer Discretionary", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "LOV": { ticker:"LOV", company:"Lovisa Holdings", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "LSF": { ticker:"LSF", company:"L1 Long Short Fund", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "LYC": { ticker:"LYC", company:"Lynas Rare Earths", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "LYL": { ticker:"LYL", company:"Lycopodium", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MAF": { ticker:"MAF", company:"MA Financial Group", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MAQ": { ticker:"MAQ", company:"Macquarie Telecom Group", sector:"Communication Services", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MCY": { ticker:"MCY", company:"Mercury NZ", sector:"Utilities", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "MEI": { ticker:"MEI", company:"Meteoric Resources", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MFF": { ticker:"MFF", company:"MFF Capital Investments", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MFG": { ticker:"MFG", company:"Magellan Financial Group", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MGH": { ticker:"MGH", company:"Maas Group Holdings", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MGR": { ticker:"MGR", company:"Mirvac Group", sector:"Real Estate", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MGX": { ticker:"MGX", company:"Mount Gibson Iron", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MHJ": { ticker:"MHJ", company:"Michael Hill International", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MIN": { ticker:"MIN", company:"Mineral Resources", sector:"Materials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MLX": { ticker:"MLX", company:"Metals X", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MND": { ticker:"MND", company:"Monadelphous Group", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MNF": { ticker:"MNF", company:"MNF Group", sector:"Communication Services", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MP1": { ticker:"MP1", company:"Megaport", sector:"Information Technology", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MPL": { ticker:"MPL", company:"Medibank Private", sector:"Health Care", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MQG": { ticker:"MQG", company:"Macquarie Group", sector:"Financials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "MTS": { ticker:"MTS", company:"Metcash", sector:"Consumer Staples", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "MVF": { ticker:"MVF", company:"Monash IVF Group", sector:"Health Care", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NAB": { ticker:"NAB", company:"National Australia Bank", sector:"Financials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "NAN": { ticker:"NAN", company:"Nanosonics", sector:"Health Care", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NCK": { ticker:"NCK", company:"Nick Scali", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NEC": { ticker:"NEC", company:"Nine Entertainment", sector:"Communication Services", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "NHC": { ticker:"NHC", company:"New Hope Corporation", sector:"Energy", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NHF": { ticker:"NHF", company:"NIB Holdings", sector:"Health Care", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "NIC": { ticker:"NIC", company:"Nickel Industries", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NSR": { ticker:"NSR", company:"National Storage REIT", sector:"Real Estate", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "NST": { ticker:"NST", company:"Northern Star Resources", sector:"Materials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:true },
  "NUF": { ticker:"NUF", company:"Nufarm", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NWH": { ticker:"NWH", company:"NRW Holdings", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NWS": { ticker:"NWS", company:"News Corporation", sector:"Communication Services", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NXL": { ticker:"NXL", company:"NUIX", sector:"Information Technology", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "NXT": { ticker:"NXT", company:"NEXTDC", sector:"Information Technology", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "OCL": { ticker:"OCL", company:"Objective Corporation", sector:"Information Technology", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "OFX": { ticker:"OFX", company:"OFX Group", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "OML": { ticker:"OML", company:"oOh!media", sector:"Communication Services", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ORA": { ticker:"ORA", company:"Orora", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ORG": { ticker:"ORG", company:"Origin Energy", sector:"Utilities", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ORI": { ticker:"ORI", company:"Orica", sector:"Materials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PAC": { ticker:"PAC", company:"Pacific Current Group", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PBH": { ticker:"PBH", company:"PointsBet Holdings", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PDC": { ticker:"PDC", company:"Predictive Discovery", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "PDN": { ticker:"PDN", company:"Paladin Energy", sector:"Energy", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PFP": { ticker:"PFP", company:"Propel Funeral Partners", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PGH": { ticker:"PGH", company:"Pact Group Holdings", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PLS": { ticker:"PLS", company:"Pilbara Minerals", sector:"Materials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "PME": { ticker:"PME", company:"Pro Medicus", sector:"Health Care", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "PMV": { ticker:"PMV", company:"Premier Investments", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "PNV": { ticker:"PNV", company:"PolyNovo", sector:"Health Care", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PPT": { ticker:"PPT", company:"Perpetual", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "PRU": { ticker:"PRU", company:"Perseus Mining", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PSI": { ticker:"PSI", company:"PSC Insurance Group", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "PTM": { ticker:"PTM", company:"Platinum Asset Management", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "QAN": { ticker:"QAN", company:"Qantas Airways", sector:"Industrials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "QBE": { ticker:"QBE", company:"QBE Insurance Group", sector:"Financials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "QUB": { ticker:"QUB", company:"QUBE Holdings", sector:"Industrials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "RBL": { ticker:"RBL", company:"Redbubble", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "REA": { ticker:"REA", company:"REA Group", sector:"Communication Services", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "REH": { ticker:"REH", company:"Reece", sector:"Industrials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "RHC": { ticker:"RHC", company:"Ramsay Health Care", sector:"Health Care", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "RIO": { ticker:"RIO", company:"Rio Tinto", sector:"Materials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "RMC": { ticker:"RMC", company:"Resimac Group", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "RMD": { ticker:"RMD", company:"ResMed", sector:"Health Care", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "RMS": { ticker:"RMS", company:"Ramelius Resources", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "RRL": { ticker:"RRL", company:"Regis Resources", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:true },
  "RWC": { ticker:"RWC", company:"Reliance Worldwide", sector:"Industrials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "S32": { ticker:"S32", company:"South32", sector:"Materials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SBM": { ticker:"SBM", company:"St Barbara", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SCG": { ticker:"SCG", company:"Scentre Group", sector:"Real Estate", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "SCP": { ticker:"SCP", company:"Shopping Centres Australasia", sector:"Real Estate", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SDF": { ticker:"SDF", company:"Steadfast Group", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "SEK": { ticker:"SEK", company:"Seek", sector:"Communication Services", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "SFR": { ticker:"SFR", company:"Sandfire Resources", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SGM": { ticker:"SGM", company:"Sims", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "SGP": { ticker:"SGP", company:"Stockland", sector:"Real Estate", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SHL": { ticker:"SHL", company:"Sonic Healthcare", sector:"Health Care", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SIQ": { ticker:"SIQ", company:"Smartgroup Corporation", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SKC": { ticker:"SKC", company:"SkyCity Entertainment", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SLK": { ticker:"SLK", company:"SeaLink Travel Group", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SLR": { ticker:"SLR", company:"Silver Lake Resources", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SNZ": { ticker:"SNZ", company:"Summerset Group Holdings", sector:"Real Estate", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SOL": { ticker:"SOL", company:"Washington H. Soul Pattinson", sector:"Financials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "SPK": { ticker:"SPK", company:"Spark New Zealand", sector:"Communication Services", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "SRG": { ticker:"SRG", company:"SRG Global", sector:"Industrials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "STO": { ticker:"STO", company:"Santos", sector:"Energy", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SUL": { ticker:"SUL", company:"Super Retail Group", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "SUN": { ticker:"SUN", company:"Suncorp Group", sector:"Financials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SVW": { ticker:"SVW", company:"Seven Group Holdings", sector:"Industrials", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "SWM": { ticker:"SWM", company:"Seven West Media", sector:"Communication Services", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "TAH": { ticker:"TAH", company:"Tabcorp Holdings", sector:"Consumer Discretionary", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "TCG": { ticker:"TCG", company:"Turaco Gold", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "TCL": { ticker:"TCL", company:"Transurban Group", sector:"Industrials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "TLS": { ticker:"TLS", company:"Telstra Group", sector:"Communication Services", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "TLT": { ticker:"TLT", company:"Tilt Renewables", sector:"Utilities", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "TLX": { ticker:"TLX", company:"Telix Pharmaceuticals", sector:"Health Care", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "TNE": { ticker:"TNE", company:"Technology One", sector:"Information Technology", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "TPG": { ticker:"TPG", company:"TPG Telecom", sector:"Communication Services", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "TPW": { ticker:"TPW", company:"Temple & Webster", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "TRS": { ticker:"TRS", company:"The Reject Shop", sector:"Consumer Discretionary", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "TWE": { ticker:"TWE", company:"Treasury Wine Estates", sector:"Consumer Staples", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "TYR": { ticker:"TYR", company:"Tyro Payments", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "VCX": { ticker:"VCX", company:"Vicinity Centres", sector:"Real Estate", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "VEA": { ticker:"VEA", company:"Viva Energy Group", sector:"Energy", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "VNT": { ticker:"VNT", company:"Ventia Services Group", sector:"Industrials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "VUL": { ticker:"VUL", company:"Vulcan Energy Resources", sector:"Materials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:true },
  "WAF": { ticker:"WAF", company:"West African Resources", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "WAM": { ticker:"WAM", company:"WAM Capital", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "WBC": { ticker:"WBC", company:"Westpac Banking Corporation", sector:"Financials", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "WDS": { ticker:"WDS", company:"Woodside Energy Group", sector:"Energy", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "WEB": { ticker:"WEB", company:"Webjet", sector:"Consumer Discretionary", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "WES": { ticker:"WES", company:"Wesfarmers", sector:"Consumer Discretionary", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "WGN": { ticker:"WGN", company:"Wagners Holding Company", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "WGX": { ticker:"WGX", company:"Westgold Resources", sector:"Materials", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:true },
  "WHC": { ticker:"WHC", company:"Whitehaven Coal", sector:"Energy", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "WLE": { ticker:"WLE", company:"WAM Leaders", sector:"Financials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "WOR": { ticker:"WOR", company:"Worley", sector:"Energy", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "WOW": { ticker:"WOW", company:"Woolworths Group", sector:"Consumer Staples", primary:"ASX 20", indices:["ASX 20","ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "WPR": { ticker:"WPR", company:"Waypoint REIT", sector:"Real Estate", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "WTC": { ticker:"WTC", company:"WiseTech Global", sector:"Information Technology", primary:"ASX 50", indices:["ASX 50","ASX 100","ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "XRO": { ticker:"XRO", company:"Xero", sector:"Information Technology", primary:"ASX 100", indices:["ASX 100","ASX 200","ASX 300","All Ordinaries"], newMar2026:false },
  "YAL": { ticker:"YAL", company:"Yancoal Australia", sector:"Energy", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ZIM": { ticker:"ZIM", company:"Zimplats Holdings", sector:"Materials", primary:"ASX 300", indices:["ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
  "ZIP": { ticker:"ZIP", company:"Zip Co", sector:"Financials", primary:"ASX 200", indices:["ASX 200","ASX 300","All Ordinaries","Small Ordinaries"], newMar2026:false },
};

// Helper: look up by ticker OR partial company name
function asxLookup(query) {
  const q = query.toUpperCase().trim();
  // Exact ticker match
  if (ASX_DATA[q]) return [ASX_DATA[q]];
  // Partial name or ticker match
  const lower = query.toLowerCase();
  return Object.values(ASX_DATA).filter(d =>
    d.ticker.toLowerCase().includes(lower) ||
    d.company.toLowerCase().includes(lower)
  );
}